//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBIA_MVCAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannedIpAdresses
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime BannedDate { get; set; }
    }
}
